### ISSUE TITLE
Trying to find link ids

### ISSUE THREAD

**Issue by agolo-alan-hogue** [shavarani/SpEL#9]
Hello,

I am trying to run SpEL and I cannot seem to find the actual link IDs.

All I really need to do right now is get predictions from the model. That is, give it text and get start index, end index, and link ID of some kind. I need to do this programmatically.

Using the example in the readme, I am processing the example sentence and I can find the indexes but not any kind of wiki id for the link.

I have included the complete code that I am running at the bottom of this issue, all from the examples. When I run it and look at the phrase_annotations for the first prediction I see this:

```
phrase_annotation.resolved_annotation = 2004
phrase_annotation.word_string = Grace Kelly
phrase_annotation.begin_character = 0
phrase_annotation.end_character = 11
```

None of these appear to be a link to any entity. "2004" is not a wikipedia ID that I can tell, nor does it link to anything that makes sense in wikidata. So how would I get the information I need to create a link?

Incidentally, when I try this:

`print(phrase_annotation.__str__())`

I get this:

```
Traceback (most recent call last):
  File "/Users/alan/repos/agolo/SpEL/src/spel_test.py", line 40, in <module>
    print(phrase_annotation.__str__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/repos/agolo/SpEL/src/spel/span_annotation.py", line 63, in __str__
    f"{self.words[0].annotations[0].idx2tag[self.resolved_annotation]}"
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SubwordAnnotation' object has no attribute 'idx2tag'
```

It would be so helpful if you could include a complete example of getting a prediction from an example text.

Here is the complete set of example code I am trying to run:

```
import sys
sys.path.append("/home/username/google_search")

# download SpEL from https://github.com/shavarani/SpEL
from transformers import AutoTokenizer
from spel.model import SpELAnnotator
from spel.configuration import device
from spel.utils import get_subword_to_word_mapping
from spel.span_annotation import WordAnnotation, PhraseAnnotation
finetuned_after_step = 4
sentence = "Grace Kelly by Mika reached the top of the UK Singles Chart in 2007."
tokenizer = AutoTokenizer.from_pretrained("roberta-base")
# ############################################# LOAD SpEL #############################################################
spel = SpELAnnotator()
spel.init_model_from_scratch(device=device)
if finetuned_after_step == 3:
    spel.shrink_classification_head_to_aida(device)
spel.load_checkpoint(None, device=device, load_from_torch_hub=True, finetuned_after_step=finetuned_after_step)
# ############################################# RUN SpEL ##############################################################
inputs = tokenizer(sentence, return_tensors="pt")
token_offsets = list(zip(inputs.encodings[0].tokens,inputs.encodings[0].offsets))
subword_annotations = spel.annotate_subword_ids(inputs.input_ids, k_for_top_k_to_keep=10, token_offsets=token_offsets)
# #################################### CREATE WORD-LEVEL ANNOTATIONS ##################################################
tokens_offsets = token_offsets[1:-1]
subword_annotations = subword_annotations[1:]
word_annotations = [WordAnnotation(subword_annotations[m[0]:m[1]], tokens_offsets[m[0]:m[1]])
                    for m in get_subword_to_word_mapping(inputs.tokens(), sentence)]
# ################################## CREATE PHRASE-LEVEL ANNOTATIONS ##################################################
phrase_annotations = []
for w in word_annotations:
    if not w.annotations:
        continue
    if phrase_annotations and phrase_annotations[-1].resolved_annotation == w.resolved_annotation:
        phrase_annotations[-1].add(w)
    else:
        phrase_annotations.append(PhraseAnnotation(w))

for phrase_annotation in phrase_annotations:
    # print(phrase_annotation.__str__())
    # except:
    #     print(f"Can't print {phrase_annotation.word_string}")

    print(phrase_annotation.resolved_annotation)

    print(phrase_annotation.word_string)

    print(dir(phrase_annotation.words))

    print(phrase_annotation.begin_character)

    print(phrase_annotation.end_character)

    print(dir(phrase_annotation))

```

**Comment by shavarani** [comment]
Hello @agolo-alan-hogue 

I appreciate your engagement with SpEL and your detailed description of the issue. Your insights highlight an area where the example code could be more explicit. I've made the suggested modifications to help you seamlessly retrieve link IDs programmatically. For this you need to change 

```
from spel.model import SpELAnnotator
```
to 
```
from spel.model import SpELAnnotator, dl_sa
```

And 

```
print(phrase_annotation.resolved_annotation)
```
To 
```
print(dl_sa.mentions_itos[phrase_annotation.resolved_annotation])
```

As well, I believe you have correctly identified a bug in PhraseAnnotation.\_\_str\_\_ , to quickly fix this bug, while we fix it in the repo, you can change:

```
subword_annotations = subword_annotations[1:]
```
to 
```
subword_annotations = subword_annotations[1:]
for sa in subword_annotations:
    sa.idx2tag = dl_sa.mentions_itos
```
Please test this update, and feel free to provide any additional feedback or adjustments you may require.
Thanks a lot
